### ISSUE TITLE
Generated BindingsBeans does not compile due to duplicate methods

### ISSUE THREAD

**Issue by saskiawagenaar** [lucmoreau/ProvToolbox#160]
Using the following simple PROV template:
```
document
        prefix var <http://openprovenance.org/var#>
        prefix vargen <http://openprovenance.org/vargen#>
        prefix ex <http://example.com#>
        bundle ex:b
                agent(var:agent,[prov:type = 'prov:Person'])
                entity(var:entity1, [prov:type="entity1"])
                entity(var:entity2, [prov:type="entity2", ex:entity1='var:entity1'])
                activity(var:activity,[prov:location = 'var:tree'])
                wasAssociatedWith(vargen:assocId; var:activity, var:agent,-)
                wasGeneratedBy(var:entity1,var:activity,-)
        endBundle
endDocument
```
and then generating BindingsBeans for them using the provtoolbox, the resulting BindingsBean will not compile due to the duplicate method  `public void addEntity1(QualifiedName arg)`:
```
// Generated Automatically by ProvToolbox for template "TestTemplate"
package nl.knmi;

import java.lang.String;
import org.openprovenance.prov.model.ProvFactory;
import org.openprovenance.prov.model.QualifiedName;
import org.openprovenance.prov.template.expander.Bindings;
import org.openprovenance.prov.template.expander.BindingsBean;

public class TestTemplateBindingsBean implements BindingsBean {
  private final Bindings bindings;

  private final ProvFactory pf;

  public TestTemplateBindingsBean(ProvFactory pf) {
    this.pf = pf;
    this.bindings = new Bindings(pf);
  }

  public void addActivity(QualifiedName arg) {
    bindings.addVariable("activity",arg);
  }

  public void addAgent(QualifiedName arg) {
    bindings.addVariable("agent",arg);
  }

  public void addEntity2(QualifiedName arg) {
    bindings.addVariable("entity2",arg);
  }

  public void addEntity1(QualifiedName arg) {
    bindings.addVariable("entity1",arg);
  }

  public void addAssocid(QualifiedName arg) {
    bindings.addVariable("assocId",arg);
  }

  public void addEntity1(QualifiedName arg) {
    bindings.addAttribute("entity1",arg);
  }

  public void addEntity1(String arg) {
    bindings.addAttribute("entity1",arg);
  }

  public void addTree(QualifiedName arg) {
    bindings.addAttribute("tree",arg);
  }

  public void addTree(String arg) {
    bindings.addAttribute("tree",arg);
  }

  public Bindings getBindings() {
    return bindings;
  }

  public String getTemplate() {
    return "src/main/resources/TestTemplate.provn";
  }
}
```

The issue seems to arise because `var:entity1` is used both as the entity id as well as an attribute. Since generated methods for adding attributes and variables both have the same naming convention, the resulting BindingsBean will have a duplicate method signature and will not compile.

**Comment by saskiawagenaar** [comment]
Dear Luc,

I'm using the following command:
`provconvert -infile <input_template_file_name> -location <input_template_directory>  -package <output_package_name> -template <name_of_template> -outfile <output_directory>`

So if you would save the template provided above as TestTemplate.provn, you could use the following command if you're in the same directory as TestTemplate.provn:
`provconvert -infile TestTemplate.provn -location . -package testpackage -template TestTemplate -outfile output`

The non-compiling binding bean will then be available in `output/testpackage/TestTemplateBindingsBean.java`

Best regards,
Saskia

**Comment by lucmoreau** [comment]
Thanks Saskia.

I was able to reproduce the problem, and added a quick fix:

In BindingsBeanGenerator,  I added the test
   if (!(allVars.contains(q)))
to ensure that the method with that signature is generated once.

for (QualifiedName q: allAtts) {
    if (!(allVars.contains(q))) builder.addMethod(generateAttMutator(q,QualifiedName.class));
    builder.addMethod(generateAttMutator(q,String.class));
}

The fix is currently in the development1_0 branch, and should make it to release shortly.

Regards,


--
Professor Luc Moreau,  Head of Department
Department of Informatics, King’s College London
Strand Campus, Bush House, 30 Aldwych, London, WC2B 4BG.
Tel: +44 207 848 6808, web: https://nms.kcl.ac.uk/luc.moreau/<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnms.kcl.ac.uk%2Fluc.moreau%2F&data=01%7C01%7Cluc.moreau%40kcl.ac.uk%7Cb86b7dc3862647040ff308d70611a6ae%7C8370cf1416f34c16b83c724071654356%7C0&sdata=Xc8kT1rwPqQ3aeCARMIkFoULEy65Bah%2FR3sjk10GUsw%3D&reserved=0>

**Comment by lucmoreau** [comment]
And a further point: if it is challenging for you to modify the ProvToolbox source code and rebuild from source, you may want to use a workaround, in which you introduce a different variable name in the template for the variable in attribute position, but the bindings give it the same value as the original variable .

Best regards,

--
Professor Luc Moreau,  Head of Department
Department of Informatics, King’s College London
Strand Campus, Bush House, 30 Aldwych, London, WC2B 4BG.
Tel: +44 207 848 6808, web: https://nms.kcl.ac.uk/luc.moreau/<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnms.kcl.ac.uk%2Fluc.moreau%2F&data=01%7C01%7Cluc.moreau%40kcl.ac.uk%7Cb86b7dc3862647040ff308d70611a6ae%7C8370cf1416f34c16b83c724071654356%7C0&sdata=Xc8kT1rwPqQ3aeCARMIkFoULEy65Bah%2FR3sjk10GUsw%3D&reserved=0>


From: Luc Moreau <luc.moreau@kcl.ac.uk>
Date: Wednesday, 2 October 2019 at 07:24
To: lucmoreau/ProvToolbox <reply@reply.github.com>, lucmoreau/ProvToolbox <ProvToolbox@noreply.github.com>
Cc: Comment <comment@noreply.github.com>, Luc Moreau <luc.moreau@kcl.ac.uk>
Subject: Re: [lucmoreau/ProvToolbox] Generated BindingsBeans does not compile due to duplicate methods (#160)


Thanks Saskia.

I was able to reproduce the problem, and added a quick fix:

In BindingsBeanGenerator,  I added the test
   if (!(allVars.contains(q)))
to ensure that the method with that signature is generated once.

for (QualifiedName q: allAtts) {
    if (!(allVars.contains(q))) builder.addMethod(generateAttMutator(q,QualifiedName.class));
    builder.addMethod(generateAttMutator(q,String.class));
}

The fix is currently in the development1_0 branch, and should make it to release shortly.

Regards,


--
Professor Luc Moreau,  Head of Department
Department of Informatics, King’s College London
Strand Campus, Bush House, 30 Aldwych, London, WC2B 4BG.
Tel: +44 207 848 6808, web: https://nms.kcl.ac.uk/luc.moreau/<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnms.kcl.ac.uk%2Fluc.moreau%2F&data=01%7C01%7Cluc.moreau%40kcl.ac.uk%7C7966f61b37954de2fc9b08d747011c4b%7C8370cf1416f34c16b83c724071654356%7C0&sdata=t%2BO9y%2BGybmTel90gEjEWURWFB4EYE0OwbDozqkx2OUE%3D&reserved=0>
