### ISSUE TITLE
Turn it into an OSGI bundle

### ISSUE THREAD

**Issue by wang70880** [lucmoreau/ProvToolbox#163]
Hi all, I want to change it to an OSGI bundle. I follow the tutorial [here:](https://lucmoreau.wordpress.com/2014/08/01/provtoolbox-tutorial-1-creating-and-saving-a-prov-document/)
I just added maven dependency part to my bundle A, which wants to use org.openprovenance.prov/prov-interop. The OSGI container I used is karaf, and my bundle has karaf-verify goal. However, the error message is shown as belows.

> [ERROR] Message: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-mylogger; type=karaf.feature; version=2.5.0.SNAPSHOT; filter:="(&(osgi.identity=openhab-binding-mylogger)(type=karaf.feature)(version>=2.5.0.SNAPSHOT))" [caused by: Unable to resolve openhab-binding-mylogger/2.5.0.SNAPSHOT: missing requirement [openhab-binding-mylogger/2.5.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.binding.mylogger; type=osgi.bundle; version="[2.5.0.202001050757,2.5.0.202001050757]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.binding.mylogger/2.5.0.202001050757: missing requirement [org.openhab.binding.mylogger/2.5.0.202001050757] osgi.wiring.package; filter:="(osgi.wiring.package=org.openprovenance.prov.interop)"]]

I checked the prov.interop in my .m2 local repo, and found that the manifest file does not export any content. I think this is the reason why the error happened. Can anyone help me solve this?

**Comment by lucmoreau** [comment]
Thanks for the email. I am not too familiar with the internal workings of OSGI. However, it is my belief that you need to configure the pom.xml files to produce bundles rather than jar files
as per

https://www.baeldung.com/osgi

Regards,

--
Professor Luc Moreau,  Head of Department
Department of Informatics, King’s College London
Strand Campus, Bush House, 30 Aldwych, London, WC2B 4BG.
Tel: +44 207 848 6808, web: https://nms.kcl.ac.uk/luc.moreau/<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnms.kcl.ac.uk%2Fluc.moreau%2F&data=01%7C01%7Cluc.moreau%40kcl.ac.uk%7Cb86b7dc3862647040ff308d70611a6ae%7C8370cf1416f34c16b83c724071654356%7C0&sdata=Xc8kT1rwPqQ3aeCARMIkFoULEy65Bah%2FR3sjk10GUsw%3D&reserved=0>

**Comment by wang70880** [comment]
Thanks Professor and I have tried. Actually, it seems that this is not a good idea, because every prov package also has many jar dependencies. So it is hard to transform it into a bundle.
