### ISSUE TITLE
Serializing / deserializing QualifiedHadMember

### ISSUE THREAD

**Issue by pbuill** [lucmoreau/ProvToolbox#174]
Hello,
I'am using QualifiedHadMember in my provenance. When serializing the Provenance Document to json everything is perfect. When i deserialize the generated provenance json back to a Document i get an IllegalArgumentException stating:  "No enum constant org.openprovenance.prov.json.ProvJSONStatement.qualifiedHadMember"
Now i'am stuck. I need to serialize and deserialize. Any ideas how to solve this.

Regards, Peter

**Comment by pbuill** [comment]
Hi Luc,
Thanks again for your quick response. I was able to build the code and everything seems to be running fine now. :-). When you are able to create a new release i will get that one. Thanks in advance.
Regards Peter

**Comment by lucmoreau** [comment]
Hi Peter,
I pushed one last night.  It should be visible now.

--
Professor Luc Moreau,  Head of Department
Department of Informatics, King’s College London
Strand Campus, Bush House, 30 Aldwych, London, WC2B 4BG.
Tel: +44 207 848 6808, web: https://nms.kcl.ac.uk/luc.moreau/<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnms.kcl.ac.uk%2Fluc.moreau%2F&data=01%7C01%7Cluc.moreau%40kcl.ac.uk%7Cb86b7dc3862647040ff308d70611a6ae%7C8370cf1416f34c16b83c724071654356%7C0&sdata=Xc8kT1rwPqQ3aeCARMIkFoULEy65Bah%2FR3sjk10GUsw%3D&reserved=0>


From: pbuill ***@***.***>
Date: Tuesday, 31 August 2021 at 15:58
To: lucmoreau/ProvToolbox ***@***.***>
Cc: Moreau, Luc ***@***.***>, Comment ***@***.***>
Subject: Re: [lucmoreau/ProvToolbox] Serializing / deserializing QualifiedHadMember (#174)

Hi Luc,
Thanks again for your quick response. I was able to build the code and everything seems to be running fine now. :-). When you are able to create a new release i will get that one. Thanks in advance.
Regards Peter

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flucmoreau%2FProvToolbox%2Fissues%2F174%23issuecomment-909316925&data=04%7C01%7Cluc.moreau%40kcl.ac.uk%7Cfdefe71e109340b1104608d96c8fc2fb%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C637660186971033062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dOP0dNIgrIcaXpM8KxmVVbnWEx2uYASv1FJ%2B2T1ZGDw%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAABCXQZXM4UJLQA4GZWOSZ3T7TUYNANCNFSM5C3QRUUQ&data=04%7C01%7Cluc.moreau%40kcl.ac.uk%7Cfdefe71e109340b1104608d96c8fc2fb%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C637660186971043024%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vwEaMCGEe4tPuET4M1Lqs5olKJP8rsor5uQhNpkK7eI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cluc.moreau%40kcl.ac.uk%7Cfdefe71e109340b1104608d96c8fc2fb%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C637660186971052984%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ont0H%2FjXdZ5rXP59Ud%2BYuMJSOHOim1vwhviUuh80%2FPw%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cluc.moreau%40kcl.ac.uk%7Cfdefe71e109340b1104608d96c8fc2fb%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C637660186971052984%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qXSxeqJZjXrlyyicdMdu2LWWlpFF2ggd9GhAtVsKOjs%3D&reserved=0>.
